# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1500)),
                ('spider', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rang', models.PositiveIntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.Query')),
            ],
        ),
    ]
