# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='image_url',
            new_name='url'
        )
    ]
