# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_query_author'),
    ]

    operations = [
        migrations.RunSQL([
            'ALTER TABLE public.finder_query RENAME COLUMN status TO statusold;',
            'ALTER TABLE public.finder_query ADD COLUMN status SMALLINT;',
            "UPDATE public.finder_query SET status = 1 WHERE statusold='done';",
            "UPDATE public.finder_query SET status = 0 WHERE statusold='create';",
            'ALTER TABLE public.finder_query DROP COLUMN statusold;',
        ], [
            'ALTER TABLE public.finder_query RENAME COLUMN status TO statusold;',
            'ALTER TABLE public.finder_query ADD COLUMN status CHARACTER VARCHAR(50);',
            "UPDATE public.finder_query SET statusold = 'done' WHERE status=1;",
            "UPDATE public.finder_query SET statusold = 'create' WHERE status=0;",
            'ALTER TABLE public.finder_query DROP COLUMN statusold;',
        ])
    ]
