# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_auto_20161003_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('way', models.CharField(max_length=1500, unique=True)),
                ('downloaded', models.BooleanField()),
            ],
        ),
    ]
