# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_zipfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfiles',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
