# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_auto_20161005_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfiles',
            old_name='data',
            new_name='date',
        ),
    ]
