# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20161005_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=150),
        ),
    ]
